name: RDP-Linux

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: ubuntu-latest
    timeout-minutes: 3600

    steps:
      - name: Install XRDP and Desktop Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y xrdp xfce4 xfce4-goodies tightvncserver
          sudo systemctl enable xrdp
          sudo systemctl start xrdp

          # Configure XRDP to use Xfce
          echo "xfce4-session" | sudo tee /etc/xrdp/startwm.sh
          sudo chmod +x /etc/xrdp/startwm.sh

          # Allow RDP through firewall
          sudo ufw allow 3389/tcp || true

      - name: Create RDP User with Secure Password
        run: |
          # Generate secure random password
          PASSWORD=$(openssl rand -base64 32 | tr -d "=+/" | cut -c1-20)

          # Create user
          sudo useradd -m -s /bin/bash rdp
          echo "rdp:$PASSWORD" | sudo chpasswd

          # Add to sudo group (optional)
          sudo usermod -aG sudo rdp

          # Save credentials to environment
          echo "RDP_CREDS=User: rdp | Password: $PASSWORD" >> $GITHUB_ENV
          echo "RDP_PASSWORD=$PASSWORD" >> $GITHUB_ENV

          # Verify user creation
          if ! id "rdp" &>/dev/null; then
              echo "User creation failed"
              exit 1
          fi

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Establish Tailscale Connection
        run: |
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-runner-linux-${{ github.run_id }}

          # Wait for Tailscale to assign an IP
          for i in {1..10}; do
              TAILSCALE_IP=$(tailscale ip -4)
              if [ -n "$TAILSCALE_IP" ]; then
                  echo "TAILSCALE_IP=$TAILSCALE_IP" >> $GITHUB_ENV
                  echo "Tailscale IP assigned: $TAILSCALE_IP"
                  break
              fi
              sleep 5
          done

          if [ -z "$TAILSCALE_IP" ]; then
              echo "Tailscale IP not assigned. Exiting."
              exit 1
          fi

      - name: Verify RDP Accessibility
        run: |
          echo "Tailscale IP: $TAILSCALE_IP"

          # Check if XRDP is running
          if ! sudo systemctl is-active --quiet xrdp; then
              echo "XRDP service is not running"
              sudo systemctl status xrdp
              exit 1
          fi

          # Check if port 3389 is listening
          if ! sudo netstat -tuln | grep ':3389'; then
              echo "Port 3389 is not listening"
              exit 1
          fi

          echo "RDP service is running and listening on port 3389"

      - name: Maintain Connection
        run: |
          echo ""
          echo "=== RDP ACCESS ==="
          echo "Address: $TAILSCALE_IP"
          echo "Username: rdp"
          echo "Password: $RDP_PASSWORD"
          echo "=================="
          echo ""

          # Keep runner active indefinitely (or until manually cancelled)
          while true; do
              echo "[$(date)] RDP Active - Use workflow cancel button to terminate"
              sleep 300
          done
